<a href="https://colab.research.google.com/github/Nitin286roxs/EDA-Feature-Engineering/blob/main/flight_price_prediction/flight_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import pands to load dataset

In [1]:
import pandas as pd

# Upload train and test dataset file

In [2]:
train_df = pd.read_excel("Data_Train.xlsx")
test_df = pd.read_excel("Test_set.xlsx")

# Concat train and test for preprocessing

In [3]:
final_df = pd.concat([train_df, test_df])

In [4]:
final_df.isnull().sum()

Airline               0
Date_of_Journey       0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
dtype: int64

# frequency of Null value is less, so that we can drop Null dataset

In [5]:
import numpy as np
np.where(final_df["Total_Stops"].isnull())

(array([9039]),)

In [6]:
np.where(final_df["Route"].isnull())

(array([9039]),)

# We can drop row=9039

In [7]:
final_df.drop([9039], axis=0, inplace=True)
final_df.isnull().sum()

Airline               0
Date_of_Journey       0
Source                0
Destination           0
Route                 0
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           0
Additional_Info       0
Price              2671
dtype: int64

# Split Date_of_Journey in differenent columns

In [8]:
final_df["Journey_Day"] = final_df["Date_of_Journey"].str.split("/").str[0]
final_df["Journey_Month"] = final_df["Date_of_Journey"].str.split("/").str[1]
final_df["Journey_Year"] = final_df["Date_of_Journey"].str.split("/").str[2]

In [9]:
final_df.drop(['Date_of_Journey'], axis=1, inplace=True)

In [10]:
#final_df['Airline'].unique()
#final_df['Airline']=final_df['Airline'].map({'IndiGo': 1, 'Air India':2 , 'Jet Airways':3 , 'SpiceJet':4,
#       'Multiple carriers':5 , 'GoAir': 6, 'Vistara': 7, 'Air Asia': 8,
#       'Vistara Premium economy':9, 'Jet Airways Business': 10,
#       'Multiple carriers Premium economy':11, 'Trujet':12})

# drop routes and Additional_Info

In [11]:
final_df.drop(['Route'], axis=1, inplace=True)
final_df.head(5)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

#convert day, month and year into int

In [12]:
final_df['Journey_Day']= final_df['Journey_Day'].astype(int)
final_df['Journey_Month']= final_df['Journey_Month'].astype(int)
final_df['Journey_Year']= final_df['Journey_Year'].astype(int)

# split  arrival_time coloumn

In [13]:
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]

In [14]:
final_df.head( 4)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year
0,IndiGo,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019

In [15]:
final_df["Arrival_hr"] = final_df['Arrival_Time'].str.split(":").str[0]
final_df["Arrival_min"] = final_df['Arrival_Time'].str.split(":").str[1]
final_df.drop(['Arrival_Time'], axis=1, inplace=True)
final_df.head(5)

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10
1,Air India,Kolkata,Banglore,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,09:25,19h,2 stops,No info,13882.0,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35

In [16]:
final_df['Arrival_hr']= final_df['Arrival_hr'].astype(int)
final_df['Arrival_min']= final_df['Arrival_min'].astype(int)

# split departure time into different columns

In [17]:
final_df["Depart_hr"] = final_df['Dep_Time'].str.split(":").str[0]
final_df["Depart_min"] = final_df['Dep_Time'].str.split(":").str[1]
final_df.drop(['Dep_Time'], axis=1, inplace=True)
final_df["Depart_hr"]= final_df["Depart_hr"].astype(int)
final_df["Depart_min"]= final_df["Depart_min"].astype(int)

In [18]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13353 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13353 non-null  object
 1   Source           13353 non-null  object
 2   Destination      13353 non-null  object
 3   Duration         13353 non-null  object
 4   Total_Stops      13353 non-null  object
 5   Additional_Info  13353 non-null  object
 6   Price            10682 non-null  float64
 7   Journey_Day      13353 non-null  int64
 8   Journey_Month    13353 non-null  int64
 9   Journey_Year     13353 non-null  int64
 10  Arrival_hr       13353 non-null  int64
 11  Arrival_min      13353 non-null  int64
 12  Depart_hr        13353 non-null  int64
 13  Depart_min       13353 non-null  int64
dtypes: float64(1), int64(7), object(6)
memory usage: 2.0+ MB

In [19]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50

# Map Number of with 0,1,2,3

In [20]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [21]:
final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop': 0, "2 stops": 2, "1 stop": 1, "3 stops": 3, "4 stops": 4})

In [22]:
final_df.head(5)
#final_df.info()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302.0,1,3,2019,21,35,16,50

# Convert duration into minutes

In [23]:
final_df['Duration_hr']=final_df['Duration'].str.split(" ").str[0].str.split("h").str[0]

In [24]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min,Duration_hr
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302.0,1,3,2019,21,35,16,50,4

In [25]:
final_df[final_df['Duration_hr']=='5m']
final_df.drop([6474], axis=0, inplace=True)
final_df.drop([2660], axis=0, inplace=True)

In [26]:
final_df['Duration_hr']= final_df['Duration_hr'].astype(int)

In [27]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min,Duration_hr
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302.0,1,3,2019,21,35,16,50,4

In [28]:
final_df['Duration_min']=final_df['Duration'].str.split(" ").str[1].str.split("m").str[0]
final_df['Duration_min']=final_df['Duration_min'].fillna(0)
final_df['Duration_min']=final_df['Duration_min'].astype(int)

In [29]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13350 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13350 non-null  object
 1   Source           13350 non-null  object
 2   Destination      13350 non-null  object
 3   Duration         13350 non-null  object
 4   Total_Stops      13350 non-null  int64
 5   Additional_Info  13350 non-null  object
 6   Price            10680 non-null  float64
 7   Journey_Day      13350 non-null  int64
 8   Journey_Month    13350 non-null  int64
 9   Journey_Year     13350 non-null  int64
 10  Arrival_hr       13350 non-null  int64
 11  Arrival_min      13350 non-null  int64
 12  Depart_hr        13350 non-null  int64
 13  Depart_min       13350 non-null  int64
 14  Duration_hr      13350 non-null  int64
 15  Duration_min     13350 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 1.7+ MB

In [30]:
final_df['Duration']=final_df["Duration_hr"]*60 + final_df["Duration_min"]

In [31]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min,Duration_hr,Duration_min
0,IndiGo,Banglore,New Delhi,170,0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,445,2,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,1140,2,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,325,1,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,285,1,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [32]:
final_df.drop(['Duration_hr', 'Duration_min'], axis=1, inplace=True)

In [33]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min
0,IndiGo,Banglore,New Delhi,170,0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,445,2,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,1140,2,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,325,1,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,285,1,No info,13302.0,1,3,2019,21,35,16,50

# Catagarical label Encoding

In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [35]:
final_df['Airline']=le.fit_transform(final_df['Airline'])
final_df['Source']=le.fit_transform(final_df['Source'])
final_df['Destination']=le.fit_transform(final_df['Destination'])
final_df['Additional_Info']=le.fit_transform(final_df['Additional_Info'])

In [36]:
final_df.head(5)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Journey_Year,Arrival_hr,Arrival_min,Depart_hr,Depart_min
0,3,0,5,170,0,8,3897.0,24,3,2019,1,10,22,20
1,1,3,0,445,2,8,7662.0,1,5,2019,13,15,5,50
2,4,2,1,1140,2,8,13882.0,9,6,2019,4,25,9,25
3,3,3,0,325,1,8,6218.0,12,5,2019,23,30,18,5
4,3,0,5,285,1,8,13302.0,1,3,2019,21,35,16,50

In [37]:
X_train=final_df.drop(['Price'], axis=1)
y_train=final_df['Price']

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, train_size=0.33, random_state=42)

# Train Model

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn import metrics

In [41]:
lr=LinearRegression()
ridge=Ridge()
dtr=DecisionTreeRegressor()
rfr=RandomForestRegressor()
etr=ExtraTreesRegressor()
br=BaggingRegressor()
svm=SVR()
xgbr=xgb()
knnr=KNeighborsRegressor()

TypeError: 'module' object is not callable